### ISSUE TITLE
How to pass options to telegram-send?

### ISSUE THREAD

**Issue by ksergey** [rahiel/supervisor-alert#2]
How to pass config option for telegram-send?

**Comment by rahiel** [comment]
The option is passed at the `command=` line in the supervisor eventlistener config file.

Did you do `sudo supervisor-alert --configure`? This would configure supervisor-alert with telegram-send automatically.

**Comment by ksergey** [comment]
@rahiel 
I want to use local user config for telegram-send. Is it possible?

**Comment by ksergey** [comment]
How to use telegram-send like below in supervisor-alert?
`telegram-send --config /home/prod/.config/telegram-send.conf`

**Comment by rahiel** [comment]
Thanks for the clarification. Supervisor-alert uses the config file at `/etc/telegram-send.conf`, so you need to do:
``` shell
sudo rm -f /etc/telegram-send.conf
sudo cp /home/prod/.config/telegram-send.conf /etc/telegram-send.conf
```
And then restart supervisor-alert: `sudo supervisorctl restart supervisor_alert`

**Comment by ksergey** [comment]
@rahiel Yes, i did it, thanks.

But actually I interested in running supervisord + supervisor-alert under regular user, becase don't want to modify root fs.
Looks like it's impossible now. Right?

**Comment by rahiel** [comment]
I think it's possible, look at the [manual configuration](https://github.com/rahiel/supervisor-alert#manual-configuration) and change the user in `/etc/supervisor/conf.d/supervisor_alert.conf` (it's in the last line). After modifying that you need to do `sudo supervisorctl reread && sudo supervisorctl update`.

**Comment by rahiel** [comment]
A different way to pass the config is by changing the `command=` line in `/etc/supervisor/conf.d/supervisor_alert.conf`:
``` shell
command=supervisor-alert -c 'telegram-send /home/prod/.config/telegram-send.conf--config'
```

**Comment by chawoo-jeon** [comment]
simply
just command this
```
telegram-send -g --config
```
`-g` option is global, saved in /etc/telegram-send.conf that telegram-send has used
