### ISSUE TITLE
problem with command in "something else" case

### ISSUE THREAD

**Issue by carlok** [rahiel/supervisor-alert#6]
Hi
supervisor-alert works fine with default telegram-send but I was not able to make it work with different command.
Documentation says:

> to use something else, for example ntfy, pass in the command:
> `command=supervisor-alert -c 'ntfy send'`

but trying with a basic bash script (even fullpath) it does not work.
Is there some format to follow?
Thanks

**Comment by rahiel** [comment]
I've just tested by setting the following in `/etc/supervisor/conf.d/supervisor_alert.conf`:
```
command=supervisor-alert -c '/home/rahiel/test.bash'
```
With the test script:
``` bash
#!/usr/bin/env bash
echo "$1" >> /tmp/supertest.log
```
The above works, and it successfully logs the process messages to `/tmp/supertest.log`. (After doing a `touch /tmp/supertest.log && sudo chown supervisor_alert /tmp/supertest.log`)

Did you make your bash script executable? The `-c` option only works with executables, maybe try again with a `chmod +x /path/to/script.bash`.

And if that isn't it, please look in `/var/log/supervisor/` for the error messages supervisor-alert is generating and share them.

**Comment by carlok** [comment]
Yes, it was about making it executable: I thought it was not necessary, due to the chain of scripts `/usr/bin/python /usr/local/bin/supervisor-alert -c my_script.sh`.
Thanks.
